# Generated by Django 4.2.14 on 2024-07-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_add',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
