# Generated by Django 4.2 on 2024-05-21 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa
                ('title', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.URLField()),
                ('categorey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorey')), # noqa
            ],
        ),
    ]
