# Generated by Django 4.2 on 2024-05-21 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa
                ('title', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')), # noqa
                ('rating_rate', models.FloatField(blank=True, null=True)),
                ('rating_count', models.ImageField(blank=True, null=True, upload_to='')), # noqa
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')), # noqa
            ],
        ),
    ]
