# Generated by Django 4.2 on 2024-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[("men's clothing", "Men's Clothing"), ("women's clothing", "Women's Clothing"), ('jewelery', 'Jewelery'), ('electronics', 'Electronics')], max_length=50)),
                ('image_url', models.URLField(max_length=400)),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('count', models.ImageField(upload_to='')),
            ],
        ),
    ]
