# Generated by Django 4.2 on 2024-05-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorey',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categorey',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
